Code cleanup to address godot4 PR comments
C7-Game/Prototype pull request #484
Opened 2024-12-30 22:28 UTC by WildWeazel

Resolved some of the open comment threads by pruning dead or commented out code and renaming things. Civ3Map.LoadTileSet did not seem to serve any purpose anymore, as it did not return or modify anything outside of the method. I did not address the question of what purpose MovingSprite serves in Civ3Unit or what its values mean.

2025-01-04 04:35 UTC, QuintillusCFC approved these changes

2025-01-04 04:35 UTC, QuintillusCFC commented on C7/Civ3Map/Civ3Map.cs
> -				if (TileIDLookup[tile.ExtraInfo.BaseTerrainFileID, 1] == 0) { LoadTileSet(tile.ExtraInfo.BaseTerrainFileID); }
Should the remaining references to TileIDLookup also be removed?  The lines that are now lines 51-52, just below this removed block, look odd now, setting the Map int[] to 0, and then looking it up via TileIDLookup which will now always be zero.

Granted I don't entirely remember the purpose of this section.  It looks like it was added back in March of '21, to implement a legacy map base terrain viewer.  But I suspect those lines can additionally be removed.  The changes are working for me in-game (and the much-decreased amount of magic numbers is nice).

2025-02-04 20:57 UTC, lexer-gamedev requested changes

2025-02-04 20:57 UTC, lexer-gamedev commented on C7/Civ3Map/Civ3Map.cs
> -				if (TileIDLookup[tile.ExtraInfo.BaseTerrainFileID, 1] == 0) { LoadTileSet(tile.ExtraInfo.BaseTerrainFileID); }
+1 to this, it doesn't seem to be used

otherwise lgtm

2025-04-10 14:16 UTC, TomWerner commented on C7/Civ3Map/Civ3Map.cs
> -				if (TileIDLookup[tile.ExtraInfo.BaseTerrainFileID, 1] == 0) { LoadTileSet(tile.ExtraInfo.BaseTerrainFileID); }
The Civ3Map class was removed a while back.

2025-04-10 14:17 UTC, TomWerner commented
I fixed the merge conflicts and am getting this merged in to clean up some of the open PRs.

2025-04-10 14:17 UTC, merged